apiVersion:v1
kind:Service
metadata:
  name:argocd-angular-app
  namespace:argocd-angular-app
  labels:
    app:argocd-angular-app

spec:
  type:loadBalancer

  selector:
    app:argocd-angular-app
  ports:
    - protocol:TCP
      name:http
      port:80
      targetPort:80
